apiVersion: v1
kind: Secret
metadata:
  name: webapp-secrets
type: Opaque
data:
  jwt-secret: Y2F0LWh1bWFuLW1hdC1tb3VzZS1kb2ctZWxlcGhhbnQtcGhvbmUtaWQ=
  jwt-expires-in: OTA=
  webapp-port : OTk5OQ==

  