apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp 
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: ankit2222/rescueradarauth:latest
        ports:
        - containerPort: 9999
        volumeMounts:
        - name: ca-pemstore
          mountPath: /etc/ssl/certs/global-bundle.pem
          subPath: global-bundle.pem
          readOnly: false
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: webapp-secrets
              key: jwt-secret
        - name: JWT_EXPIRES_IN
          valueFrom:
            secretKeyRef:
              name: webapp-secrets
              key: jwt-expires-in
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: webapp-secrets
              key: webapp-port
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      volumes:
      - name: ca-pemstore
        configMap:
          name: ca-pemstore
      
---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 9999
    nodePort: 30001


---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: webapp  # Match labels of your PostgreSQL pod(s)
  ports:
    - protocol: TCP
      port: 5432  # PostgreSQL default port
      targetPort: 5432
  type: LoadBalancer  # Use LoadBalancer to expose externally
